### ISSUE TITLE
Document how you are taking the full screen screenshot of the notebook (in markdown on a GitHub page)

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/k8-data-visualization#13]
Document how you are taking the full screen screenshot of the notebook (in markdown on a GitHub page)

**Comment by chrisdiao** [comment]
@baker371 , please grab this issue.

**Comment by baker371** [comment]
This has been completed.

**Comment by dtollaku** [comment]
@baker371 all PRs needs to be connected with an issue. Can you link this one with the PR you have created.

**Comment by dtollaku** [comment]
I connected with you PR [https://github.com/filetrust/k8-data-visualization/pull/16](url). There are some changes requested on this PR. When PR will be merged this issue can be closed.
