### ISSUE TITLE
Create Jupiter notebook and visualization ONLY for the repos current linked to this Slack organization

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/k8-data-visualization#14]
Create Jupiter notebook and visualization ONLY for the repos current linked to this Slack organization (see slack channels for the names)

**Comment by baker371** [comment]
@chrisdiao , Yes all the repos  referenced here belong to the organisation according to the rules of engagement document. So I think there is no need of changing, I think #14 was a miscommunication.
