### ISSUE TITLE
8. Setup a serverless workflow

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/k8-data-visualization#34]
Setup a serverless workflow which gets triggered with GitHub issues events 
**Note:** Need to evaluate if we can use github actions or else go with AWS

**Comment by baker371** [comment]
@chrisdiao we can use github actions and these are the different issue events, do you need a work flow that captures all of them or some, and what is the expected outcome, the workflow gets triggered to do what?

- opened
- edited
- deleted
- transferred
- pinned
- unpinned
- closed
- reopened
- assigned
- unassigned
- labeled
- unlabeled
- locked
- unlocked
- milestoned
- demilestoned

**Comment by chrisdiao** [comment]
@baker371 , please coordinate with Anish. I saw inputs from him last Aug 29.

**Comment by chrisdiao** [comment]
Issue moved to [filetrust/k8-slack-bot #18](https://github.com/filetrust/k8-slack-bot/issues/18) via [**ZenHub**](https://www.zenhub.com/)
