### ISSUE TITLE
11. The raw issue data, to be consumed by the Jupyter Notebooks notebook.

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/k8-data-visualization#41]
The raw issue data, to be consumed by the Jupyter Notebooks notebook.

**Comment by amanthegeek** [comment]
Here it is https://github.com/filetrust/k8-data-visualization/blob/master/upwork-devs/aman-kumar/Issues_visuals.ipynb

**Comment by chrisdiao** [comment]
Issue moved to [filetrust/k8-slack-bot #27](https://github.com/filetrust/k8-slack-bot/issues/27) via [**ZenHub**](https://www.zenhub.com/)
