### ISSUE TITLE
12. The data stored on a separate repo will allow the Developers working on the visualization to not have to deal with the data collection.

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/k8-data-visualization#42]
The data stored on a separate repo will allow the Developers working on the visualization to not have to deal with the data collection.

**Comment by baker371** [comment]
@chrisdiao  I do not understand this issue. Can you please elaborate?

**Comment by chrisdiao** [comment]
@dinis-cruz-gw , can you please help us on this? Thanks!

**Comment by chrisdiao** [comment]
Issue moved to [filetrust/k8-slack-bot #26](https://github.com/filetrust/k8-slack-bot/issues/26) via [**ZenHub**](https://www.zenhub.com/)
