### ISSUE TITLE
Create Architecture Diagram for Data Visualization Project

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/k8-data-visualization#50]

**Comment by chrisdiao** [comment]
@manish2kcoder , can we have an update on this please?

**Comment by manish2kcoder** [comment]
hi @chrisdiao yes this is done. The architecture was created and shared, later pushed to the slackbot channel. Git data visualization has moved to the p-slackbot team and data-visualization has been changed to a team that is going to serve general visualization requests. Better we create and close this task in p-slackbot. Closing this task now. Architecture is as below



![owasp_git_apis (1)-min](https://user-images.githubusercontent.com/12497914/92945991-b26b1500-f473-11ea-9c42-f3ec0dd0858c.png)
