### ISSUE TITLE
Create PR report in Jupyter Notebook

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/k8-data-visualization#51]
**List all PR's for each repo below:**
- https://github.com/filetrust/k8-reverse-proxy
- https://github.com/filetrust/k8-traffic-generator
- https://github.com/filetrust/k8-glasswall-rebuild
- https://github.com/filetrust/k8-data-visualization
- https://github.com/filetrust/k8-performance-use-cases
- https://github.com/filetrust/rebuild-k8s-filetypedetection

Note: This could expanded in the future

**Criteria:**
In Zenhub, the pipeline should be under "Peer Review"

**Expected Output:**
- Repository Name
- PR Link
- Reviewer
- Date Created

**Comment by lucia15** [comment]
![sample_output](https://user-images.githubusercontent.com/8679969/92956813-e6c3de80-f43d-11ea-9bc9-fbc5f29335a7.png)
