### ISSUE TITLE
Need Glasswall Zenhub account(token)

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/k8-data-visualization#57]
@dtollaku , this request is similar to issue #49 but this time we need zenhub token.

Steps in generating the token:
1. Open Zenhub
2. At the lower left of the screen, select your account name
3. Select Manage Organization
3. Select API Tokens
4. Click Generate New Token

**Comment by dtollaku** [comment]
@chrisdiao Here is the token
c3bd1d296da6c51afa652dcd51cbd33f712ebec8bde25cd9b05d2b4279b8003a1226cb2e2da152fd
