### ISSUE TITLE
Need a way to visualise way Open PRs there are to review

### ISSUE THREAD

**Issue by markband** [filetrust/k8-data-visualization#6]
Dinis: need a way to visualise way Open PRs there are for me to review
for example this is the status of PRs in one of the project (which means that is nothing for me to do there)

![image.png](https://images.zenhubusercontent.com/5f438b5476b315207ae7fe5c/938c5a93-885f-4ca7-9df0-dab3934326d5)

**Comment by baker371** [comment]
@mnjenga2  is already working on this, check in progress. This is a duplication of tasks.
