### ISSUE TITLE
Add support for running Jupyter Notebooks docker image locally 

### ISSUE THREAD

**Issue by markband** [filetrust/k8-data-visualization#7]
Add support for running Jupyter Notebooks docker image locally (mounting the current source code as the root of the notebooks folder)
this will allow us to run the Jupyter UI (normal and Labs) locally

**Comment by chrisdiao** [comment]
@rajmbcoderx , may we know when will this be completed?

**Comment by rajmbcoderx** [comment]
@chrisdiao I have been working on it and should complete in sometime

**Comment by rajmbcoderx** [comment]
![console](https://user-images.githubusercontent.com/20489970/92257256-8b03cd80-eef2-11ea-8cbf-3a86e68e5b5b.jpeg)

_Run docker build -t local-jupyter ._

![console2](https://user-images.githubusercontent.com/20489970/92257337-aec71380-eef2-11ea-8dce-5f9cfa4e01d6.jpeg)
_Run "docker run -it --rm -p 8888:8888 -v ${PWD}:/home/jovyan1/ local-jupyter"_

_Open this locally - http://127.0.0.1:8888/?token=0cfb008e2979f1ec62c612cca4b31929e3d28176f626459a_
![browser_output](https://user-images.githubusercontent.com/20489970/92257404-cef6d280-eef2-11ea-84d2-6e9fb5608ed8.jpeg)

_Open in browser and write/upload notebooks_

**Comment by rajmbcoderx** [comment]
This is the PR - https://github.com/filetrust/k8-data-visualization/pull/47
Markdown updated and a minor change to the script to start notebooks to mount work dir with notebooks root.

**Comment by chrisdiao** [comment]
> This is the PR - #47
> Markdown updated and a minor change to the script to start notebooks to mount work dir with notebooks root.

Noted on this @rajmbcoderx , already linked issue #47 with this issue.
Thanks!
